# Generated by Django 4.1.2 on 2022-11-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskone',
            name='backend',
            field=models.BooleanField(),
        ),
    ]
