# Generated by Django 4.1.2 on 2022-11-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_alter_taskone_backend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskone',
            name='backend',
            field=models.BooleanField(default=True),
        ),
    ]
